[package]
name = "stakehaven"
version = "1.0.0"
authors = ["Meet Rathod"]

[addresses]
admin="0xb070a562582244953a72d187bd05ee837e18829f39d29fd8b4b4e9b3e407e5a5"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
